### ISSUE TITLE
Training settings

### ISSUE THREAD

**Issue by hulianyuyy** [YiLunLee/missing_aware_prompts#12]
Many thanks for your great work! May i ask how many GPUs are needed during training?

**Comment by YiLunLee** [comment]
Thank you for your question.

I use 2 NVIDIA GTX 2080Ti GPUs with per_gpu_batchsize=2 for MM-IMDb dataset.  However, the number of GPUs depends on your choice. You can adjust the config ``per_gpu_batchsize`` and ``num_gpus`` to fit your environment.
