### ISSUE TITLE
a training problem

### ISSUE THREAD

**Issue by ZunxiaoXu** [YiLunLee/missing_aware_prompts#16]
hi, thanks for your great work! I try to train the model based on the hateful dataset, but when the first epoch reaches 34%, the training process will always get stuck here. I don't know why. Have you encountered this situation?

**Comment by ZunxiaoXu** [comment]
I solved this problem by setting only train with a single gpu

**Comment by ALEX13679173326** [comment]
I also encountered the same problem. Using one GPU is too slow. Is there a solution for running on multiple GPUs?
