### ISSUE TITLE
About dataset hateful_memes

### ISSUE THREAD

**Issue by hulianyuyy** [YiLunLee/missing_aware_prompts#19]
Name 'text_aug_dir' is not defined in line 26 in write_hatefulmemes.py. How to solve it?

**Comment by Trae1ounG** [comment]
Maybe just # it ,there is not contextual use in the code and it can still run successfully.

**Comment by herkerser** [comment]
How to get the test labels of hateful_memes dataset, would you mind sharing the link to download the annotation file?

**Comment by Trae1ounG** [comment]
> How to get the test labels of hateful_memes dataset, would you mind sharing the link to download the annotation file?

In the file `Data.md`,it says to download the file `test_seen.jsonl` from https://www.kaggle.com/datasets/williamberrios/hateful-memes/data, I use this way.

**Comment by herkerser** [comment]
Thank you so much for your kind rely!
best regards




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月29日(星期三) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YiLunLee/missing_aware_prompts] About dataset hateful_memes (Issue #19)





  
How to get the test labels of hateful_memes dataset, would you mind sharing the link to download the annotation file?
  
In the file Data.md,it says to download the file test_seen.jsonl from https://www.kaggle.com/datasets/williamberrios/hateful-memes/data, I use this way.
