### ISSUE TITLE
Hateful Meme testset

### ISSUE THREAD

**Issue by jasonchengqs** [YiLunLee/missing_aware_prompts#6]
Thank you for releasing the code for your interesting paper! I was trying to test on the Hateful-meme dataset. However, it seems the testset of this dataset does not contain the 'label' field, which is required for the write_*py function. Could you kindly let me know where to download the labels for the test set?

**Comment by YiLunLee** [comment]
Thank you for your question. 
That is my mistake, I forgot that the dataset from [Kaggle link](https://www.kaggle.com/datasets/parthplc/facebook-hateful-meme-dataset) in Data.md does not have labels for the test set. However, the test set is actually the same as test_seen.jsonl in [this link](https://www.kaggle.com/datasets/williamberrios/hateful-memes), you can directly download the test_seen.jsonl file here and use it (of course you should rename it as test.jsonl or revise the write_*.py file).

**Comment by jasonchengqs** [comment]
Thank you!
